#!/bin/bash

SCRIPT=`readlink -f ${BASH_SOURCE[0]}`
root=$( dirname  "${SCRIPT}")

if [[ $(id -u) -ne 0 ]]; then 
        echo "[ERROR]: Please run as root"
        exit 1
fi

service nginx status > /dev/null
if [ $? -ne 0 ]; then
    echo "[ERROR]: nginx is not running"
    exit 1
fi

semaphore_path=$root/maintenance_mode.semaphore
if [ -e $semaphore_path ]; then
        echo '[WARNING]: Already in maintenance_mode!!!!'
else
	touch $semaphore_path
	service nginx force-reload
        echo '[SUCCESS]: NGINX is in maintenance_mode now!!!!'
fi
